eureka-discovery-service:
  credentials:
    user: mario
    password: "{cipher}AQAcB5NeMCU1GEaTBEROGJQ0AYf46vZ0I8WNOaha4vWhG5TBwqCCjw95lgxPu55GOG4hUyxxgd5Jm7PcjUA1lOmm/VY/r2DF+mJ7cIplMdWd41rFEka0lHf73NZRK+qZQrpF89BTHLp8YWxL7J83kfXQzMQ37vNAh4PlDHYkxSTH0kh63wvToe6lWzWildDypQRjDC9cFGoZk1MGFVsC4MzlUa089HwXsWIXYd3FI/mZtmcAd/987ErK4uapg6GCDihSGqdA4wPP2GOrN2WFpj09aYahhzuhGj3GY7JCttNPmrLVndh35JpsSlMTyZqlgkEFFJlzmgSPFAGJ2jZ5TA1BGU5Gg3H2sMD0JP/ZQ83BHVmrpoq1BvC9EohIwbwH2K0="

eureka:
  client:
    service-url:
      defaultZone: http://${eureka-discovery-service.credentials.user}:${eureka-discovery-service.credentials.password}@localhost:8090/eureka

app:
  login:
    url: /users/authentication
  jwt:
    identifier: token
    expiration: 3600000
    secret: '{cipher}AQBSySV1mVcEccI8y0aFNZOF9YF2Mzan0lFMum379yXY0HL/zP7kD574erbPVcqG6xBiH1J64dpyZ6hQ3koxlOlD0yKlney0VBGsQBCmjHORhOce+H+pTZvnpdNFF94sctAtrS42v0EH20+WOJRO2eXn3yhH7j8R+F1CtHlvaGrTKhz+pQI9SONCJV0iMp51wQd/eaPH9vNEgbLxu9NCEWhUTOMcU5WfIBBIZpEK+WtOieTj1WW0/PSxe60toCC9eAP5UypjTvxymsee1IT9gLibRiizW78BZc9YoVsrEaFNQHIoTas3OjxjZ+DPNxX2geZeNZFwwqnNXKdYmLOBeaHa5T8dzfvXUz93rzGUte9FJHgzNnpf52Tzh32hbTPUFCA='
